export const tasks = [
  {
    id: "task_001",
    title: "Build a yield farm dApp on Soroban",
    description: "Create a simple yield farming smart contract using Soroban SDK. The contract should allow users to deposit XLM, earn rewards over time, and withdraw their stake plus rewards. Include proper error handling and event emission.",
    category: "DeFi",
    rewardXlm: 150,
    rewardUsd: 12.5,
    deadline: "2026-06-15T00:00:00Z",
    maxSubmissions: 5,
    currentSubmissions: 2,
    status: "active",
    createdBy: "admin_001",
    createdAt: "2026-01-01T00:00:00Z",
    proofRequirements: [
      "GitHub repository link",
      "Deployed contract address on testnet",
      "Short demo video (2 min max)",
    ],
  },
  {
    id: "task_002",
    title: "Write Soroban SDK documentation",
    description: "Create comprehensive developer documentation for the Soroban SDK covering contract deployment, invocation patterns, and common pitfalls. Should include code examples for each section.",
    category: "Documentation",
    rewardXlm: 80,
    rewardUsd: 6.67,
    deadline: "2026-05-20T00:00:00Z",
    maxSubmissions: 3,
    currentSubmissions: 1,
    status: "active",
    createdBy: "admin_001",
    createdAt: "2026-01-05T00:00:00Z",
    proofRequirements: [
      "Published documentation link (GitBook, Notion, or similar)",
      "Minimum 2000 words",
      "At least 5 code examples",
    ],
  },
  {
    id: "task_003",
    title: "Design DVS landing page UI kit",
    description: "Create a complete Figma UI kit for the DVS platform including all components, color tokens, typography scale, and responsive layouts for landing, dashboard, and certificate pages.",
    category: "Design",
    rewardXlm: 120,
    rewardUsd: 10.0,
    deadline: "2026-04-30T00:00:00Z",
    maxSubmissions: 2,
    currentSubmissions: 0,
    status: "active",
    createdBy: "admin_001",
    createdAt: "2026-01-10T00:00:00Z",
    proofRequirements: [
      "Figma file link (view access)",
      "Component library with variants",
      "Mobile + desktop layouts",
    ],
  },
  {
    id: "task_004",
    title: "Build a Stellar DEX integration",
    description: "Integrate Stellar DEX trading functionality into a React frontend. Users should be able to view order books, place buy/sell orders, and see their trade history using Stellar SDK.",
    category: "Development",
    rewardXlm: 200,
    rewardUsd: 16.67,
    deadline: "2026-07-01T00:00:00Z",
    maxSubmissions: 4,
    currentSubmissions: 3,
    status: "active",
    createdBy: "admin_001",
    createdAt: "2026-01-15T00:00:00Z",
    proofRequirements: [
      "GitHub repository link",
      "Live demo URL",
      "README with setup instructions",
    ],
  },
  {
    id: "task_005",
    title: "Research DeFi yield strategies on Stellar",
    description: "Conduct a thorough research report on existing and potential DeFi yield strategies that can be implemented on the Stellar network using Soroban smart contracts.",
    category: "Research",
    rewardXlm: 60,
    rewardUsd: 5.0,
    deadline: "2026-05-10T00:00:00Z",
    maxSubmissions: 5,
    currentSubmissions: 2,
    status: "active",
    createdBy: "admin_001",
    createdAt: "2026-01-20T00:00:00Z",
    proofRequirements: [
      "Research report (PDF or Google Doc)",
      "Minimum 3000 words",
      "Citations and references",
    ],
  },
  {
    id: "task_006",
    title: "Community tutorial: Getting started with Freighter",
    description: "Create a beginner-friendly tutorial series (blog posts or video) walking new users through installing Freighter wallet, creating an account, and making their first Stellar transaction.",
    category: "Community",
    rewardXlm: 50,
    rewardUsd: 4.17,
    deadline: "2026-04-15T00:00:00Z",
    maxSubmissions: 3,
    currentSubmissions: 1,
    status: "paused",
    createdBy: "admin_001",
    createdAt: "2026-01-25T00:00:00Z",
    proofRequirements: [
      "Published tutorial link",
      "Minimum 1500 words or 10-minute video",
    ],
  },
]

export const submissions = [
  {
    id: "sub_001",
    taskId: "task_001",
    taskTitle: "Build a yield farm dApp on Soroban",
    userId: "user_001",
    userName: "Alex Wong",
    userWallet: "GBXXX...1234",
    proofText: "I built the yield farming contract using Soroban SDK v0.9. The contract supports deposit, withdraw, and claim_rewards functions. All tests pass on testnet.",
    files: ["demo.mp4", "README.md"],
    status: "approved",
    submittedAt: "2026-02-10T14:30:00Z",
    reviewedAt: "2026-02-12T09:00:00Z",
    adminFeedback: "Excellent work! Contract is well-structured and tests are comprehensive.",
    rewardXlm: 150,
    txHash: "abc123def456ghi789",
  },
  {
    id: "sub_002",
    taskId: "task_002",
    taskTitle: "Write Soroban SDK documentation",
    userId: "user_001",
    userName: "Alex Wong",
    userWallet: "GBXXX...1234",
    proofText: "Completed the Soroban SDK documentation covering all major topics. Published on GitBook with 2500 words and 7 code examples.",
    files: ["docs-link.txt"],
    status: "pending",
    submittedAt: "2026-03-01T10:00:00Z",
    reviewedAt: null,
    adminFeedback: null,
    rewardXlm: 80,
    txHash: null,
  },
  {
    id: "sub_003",
    taskId: "task_003",
    taskTitle: "Design DVS landing page UI kit",
    userId: "user_001",
    userName: "Alex Wong",
    userWallet: "GBXXX...1234",
    proofText: "Created a full Figma UI kit with 40+ components, 3 color themes, and responsive layouts for all major pages.",
    files: ["figma-link.txt", "preview.png"],
    status: "rejected",
    submittedAt: "2026-02-20T16:00:00Z",
    reviewedAt: "2026-02-22T11:00:00Z",
    adminFeedback: "Good start but missing mobile layouts for the dashboard. Please add responsive variants and resubmit.",
    rewardXlm: 120,
    txHash: null,
  },
  {
    id: "sub_004",
    taskId: "task_004",
    taskTitle: "Build a Stellar DEX integration",
    userId: "user_002",
    userName: "Maria Santos",
    userWallet: "GCYYY...5678",
    proofText: "Built a full DEX integration with order book display, trade placement, and history. Live demo deployed on Vercel.",
    files: ["demo-url.txt", "repo-link.txt"],
    status: "under_review",
    submittedAt: "2026-03-05T08:00:00Z",
    reviewedAt: null,
    adminFeedback: null,
    rewardXlm: 200,
    txHash: null,
  },
  {
    id: "sub_005",
    taskId: "task_005",
    taskTitle: "Research DeFi yield strategies on Stellar",
    userId: "user_002",
    userName: "Maria Santos",
    userWallet: "GCYYY...5678",
    proofText: "Completed a 3500-word research report covering 6 yield strategies with citations from 12 academic and industry sources.",
    files: ["research-report.pdf"],
    status: "pending",
    submittedAt: "2026-03-08T12:00:00Z",
    reviewedAt: null,
    adminFeedback: null,
    rewardXlm: 60,
    txHash: null,
  },
]

export const certificates = [
  {
    id: "cert_001",
    taskId: "task_001",
    taskTitle: "Build a yield farm dApp on Soroban",
    userId: "user_001",
    userName: "Alex Wong",
    userWallet: "GBXXX...1234",
    issuedBy: "admin_001",
    issuerName: "DVS Admin",
    issuedAt: "2026-02-12T09:00:00Z",
    rewardXlm: 150,
    txHash: "abc123def456ghi789",
    blockNumber: 48291034,
    certificateHash: "0xDVS89f3e2a1b4c5d6e7f8",
  },
  {
    id: "cert_002",
    taskId: "task_004",
    taskTitle: "Build a Stellar DEX integration",
    userId: "user_001",
    userName: "Alex Wong",
    userWallet: "GBXXX...1234",
    issuedBy: "admin_001",
    issuerName: "DVS Admin",
    issuedAt: "2026-01-28T14:00:00Z",
    rewardXlm: 200,
    txHash: "def456ghi789jkl012",
    blockNumber: 48100221,
    certificateHash: "0xDVS12a3b4c5d6e7f8g9",
  },
  {
    id: "cert_003",
    taskId: "task_005",
    taskTitle: "Research DeFi yield strategies on Stellar",
    userId: "user_001",
    userName: "Alex Wong",
    userWallet: "GBXXX...1234",
    issuedBy: "admin_001",
    issuerName: "DVS Admin",
    issuedAt: "2026-01-15T11:00:00Z",
    rewardXlm: 60,
    txHash: "ghi789jkl012mno345",
    blockNumber: 47980112,
    certificateHash: "0xDVS34c5d6e7f8g9h0i1",
  },
]

export const users = [
  {
    id: "user_001",
    name: "Alex Wong",
    email: "alex@example.com",
    role: "user",
    walletAddress: "GBXXX...1234",
    tasksCompleted: 7,
    certificatesCount: 5,
    totalXlmEarned: 620,
    joinedAt: "2025-07-01T00:00:00Z",
    status: "active",
  },
  {
    id: "user_002",
    name: "Maria Santos",
    email: "maria@example.com",
    role: "user",
    walletAddress: "GCYYY...5678",
    tasksCompleted: 3,
    certificatesCount: 2,
    totalXlmEarned: 280,
    joinedAt: "2025-08-15T00:00:00Z",
    status: "active",
  },
  {
    id: "admin_001",
    name: "DVS Admin",
    email: "admin@dvs.io",
    role: "admin",
    walletAddress: "GCYYY...5678",
    tasksCreated: 12,
    totalRewarded: 1840,
    joinedAt: "2025-06-01T00:00:00Z",
    status: "active",
  },
]

export const activityFeed = [
  {
    id: "evt_001",
    type: "certificate_minted",
    message: "Certificate minted — #cert_001",
    userId: "user_001",
    txHash: "abc123...",
    timestamp: "2026-02-12T09:00:00Z",
  },
  {
    id: "evt_002",
    type: "reward_sent",
    message: "Reward sent — 150 XLM → Alex Wong",
    userId: "user_001",
    txHash: "def456...",
    timestamp: "2026-02-12T09:00:00Z",
  },
  {
    id: "evt_003",
    type: "proof_submitted",
    message: "Proof submitted — Soroban SDK docs",
    userId: "user_001",
    txHash: null,
    timestamp: "2026-03-01T10:00:00Z",
  },
  {
    id: "evt_004",
    type: "task_created",
    message: "New task created — Stellar DEX integration",
    userId: "admin_001",
    txHash: null,
    timestamp: "2026-01-15T08:00:00Z",
  },
  {
    id: "evt_005",
    type: "submission_approved",
    message: "Submission approved — yield farm dApp",
    userId: "admin_001",
    txHash: "abc123...",
    timestamp: "2026-02-12T09:00:00Z",
  },
  {
    id: "evt_006",
    type: "user_joined",
    message: "New user joined — Maria Santos",
    userId: "user_002",
    txHash: null,
    timestamp: "2025-08-15T00:00:00Z",
  },
]

export const stats = {
  totalTasksCreated: 24,
  totalCertificatesMinted: 87,
  totalXlmDistributed: 12450,
  poolBalance: 850,
}
